fix: add ability to use working proposals api implementation #LSC-330
lidofinance/terra-repositories pull request #4
Opened 2022-04-19 10:44 UTC by NeverHappened

2022-04-21 12:28 UTC, oopcode approved these changes

2022-04-21 14:25 UTC, sotnikov-s requested changes

2022-04-21 14:25 UTC, sotnikov-s commented on proposals/repository.go
> +func (r *Repository) FetchDeposit2(ctx context.Context) ([]*query.ProposalsOKBodyProposalsItems0, error) {
don't really like these Fetch...1 and Fetch...2 — the difference is very concealed. could you please expose the differences? ideally reflect the difference in both method names and explicitly in comments

I mean you've preferred one over another during the task, right? the reason for that could imply a good description

2022-04-21 14:25 UTC, sotnikov-s commented on proposals/repository.go
> +// TODO: check that return types correlate with swagger types (query.ProposalsOKBodyProposalsItems0)
would be great to have tests for the new methods

2022-04-21 14:25 UTC, sotnikov-s commented on proposals/repository.go
> +			return res, fmt.Errorf("failed to get proposals with {%s} status: %s\"", err, status)
`\"` seems to be redundant
`%w` instead of `%s`
return nil, not res

2022-04-21 14:34 UTC, sotnikov-s commented on proposals/repository.go
> +func (r *Repository) FetchDeposit2(ctx context.Context) ([]*query.ProposalsOKBodyProposalsItems0, error) {
or, as swelf suggested in another PR, we can just get rid of the old ones :) as far as I can see, it's only governance bot and proposal checker that uses the repo so far

2022-04-22 06:46 UTC, foxpy reviewed
Can't really say much besides API functions suffixed with `2`, that's not cool.

2022-04-22 08:55 UTC, sotnikov-s approved these changes

2022-04-22 08:55 UTC, sotnikov-s commented on proposals/repository_test.go
> +		//}
why keep commented lines?

2022-04-22 08:55 UTC, sotnikov-s commented on proposals/repository_test.go
> +		assert.NotNilf(t, proposal.TotalDeposit[0].Amount, "proposal content amount must not be empty")
proposal `content`->`total deposit` amount. same for denom above

2022-04-22 09:10 UTC, foxpy approved these changes

2022-04-22 09:23 UTC, merged